### ISSUE TITLE
Can you bump prettier into 1.19.1?

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [tmknom/prettier#9]
Hi @tmknom,

It seems you are [6 releases away](https://github.com/prettier/prettier/releases) from [latest stable release](https://github.com/prettier/prettier/releases/1.19.1). Do you have any plans to bump it into the latest one?

Thanks in advance.

**Comment by akainic** [comment]
Hey @tmknom, our team is also wondering if the prettier version can be updated to the latest. We are trying to use a JavaScript feature (optional chaining) that prettier added support for in v1.19.0. Without updating the prettier version in this library to v1.19.0, we get syntax errors that causes the prettier check to fail, blocking us from merging in the change (since we're using this library in our CI runner).

Thanks!

**Comment by AndreiJirohHaliliDev2006** [comment]
@akainic It seems your team needs to do some rework on the code, right?

**Comment by tmknom** [comment]
@AndreiJirohHaliliDev2006 @akainic
Sorry for the late reply.

The 1.19.1 version of Docker Image created.
And the latest 2.0.5 version created also.
Please see https://hub.docker.com/r/tmknom/prettier/tags.

Thanks.

**Comment by AndreiJirohHaliliDev2006** [comment]
> @AndreiJirohHaliliDev2006 @akainic
> Sorry for the late reply.
> 
> The 1.19.1 version of Docker Image created.
> And the latest 2.0.5 version created also.
> Please see https://hub.docker.com/r/tmknom/prettier/tags.
> 
> Thanks.

@tmknom Good. I am will closing this issue because the base dependency (`prettier`) is now bumped into 1.19.1+. Thank you.
